name: Main

on:
  pull_request:
    branches: [master]

jobs:
  testAndBuild:
    name: "Test and build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
        with:
          gh-packages-token: ${{ secrets.GH_PACKAGES_TOKEN }}

      - run: nr lint

      - run: nr test
        env:
          CI: "true"

      - run: nr build
